{{- if not .Values.postgres.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fireseed-postgres
  namespace: {{ include "fireseed.namespace" . }}
  labels:
    app: fireseed-postgres
    {{- include "fireseed.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: fireseed-postgres
{{- end }}
